[package]
name = "minecraft-launcher-lib"
version = "0.9.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-util = "0.7.11"
tokio = { version = "1.38", features = [ "test-util", "macros", "fs", "process","sync"] }
futures = "0.3.30"
log = "0.4.22"
sha1 = "0.10.6"
lazy_static = "1.5.0"
uuid = { version= "1.9.1", features = ["v4","serde"]}
os_info = { version = "3", default-features = false }
sysinfo = "0.30.12"
regex = "1.10.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
thiserror = "1.0"
async_zip = { version = "0.0.17", features = ["tokio","tokio-fs","deflate"] }
sanitize-filename = "0.5.0"
hex = "0.4.3"
urlencoding = "2.1.3"

sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "macros","chrono", "migrate"]}

chrono = { version = "0.4.38", features = ["serde"] }
#async-compression = { version = "0.4.10", features = ["lzma","tokio"]}
normalize-path = "0.2.1"
lazy-regex = "3.1.0"
[dev-dependencies]
env_logger = "0.11"
