[package]
name = "minecraft-launcher-lib"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-util = "0.7.11"
tokio = { version = "1.37", features = [ "test-util", "macros", "fs", "process","sync"] }
futures = "0.3.30"
log = "0.4.21"
sha1 = "0.10.6"
lazy_static = "1.4.0"
os_info = { version = "3", default-features = false }
regex = "1.10.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
thiserror = "1.0"
async_zip = { version = "0.0.17", features = ["tokio","tokio-fs","lzma"] }
sanitize-filename = "0.5.0"
hex = "0.4.3"
async-compression = { version = "0.4.10", features = ["lzma","tokio"]}
normalize-path = "0.2.1"
lazy-regex = "3.1.0"
[dev-dependencies]
env_logger = "0.11"
