[package]
name = "minecraft-launcher-lib"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = [ "test-util", "macros", "fs", "process" ] }
futures = "0.3.26"
log = "0.4.17"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.10.0"
