[package]
name = "minecraft-launcher-lib"
version = "0.8.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-util = "0.7.8"
tokio = { version = "1.26.0", features = [ "test-util", "macros", "fs", "process","sync"] }
futures = "0.3.27"
log = "0.4.17"
sha1 = "0.10.5"
os_info = { version = "3", default-features = false }
regex = "1.7.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1.0"
async_zip = { version = "0.0.15", features = ["tokio","tokio-fs","lzma"] }
sanitize-filename = "0.4.0"
hex = "0.4.3"
async-compression = { version = "0.4.0", features = ["lzma","tokio"]}
normalize-path = "0.2.0"

[dev-dependencies]
env_logger = "0.10.0"
