[package]
name = "app"
version = "0.5.0+9"
description = "A Tauri App"
authors = ["Collin Blosser"]
license = ""
repository = "https://github.com/VisualSource/rusty-mc-launcher"
default-run = "app"
edition = "2021"
rust-version = "1.78.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
tokio = { version = "1.37.0", features = ["sync"] }
log = "0.4.21"

thiserror = "1.0"
serde_json = "1.0"
time = "0.3.36"
httparse = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
#tauri-plugin-sqlite = { git="https://github.com/lzdyes/tauri-plugin-sqlite", tag = "v0.1.1" }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-deep-link = { git = "https://github.com/FabianLars/tauri-plugin-deep-link" }
tauri = { version = "1.6.2", features = [ "process-exit", "fs-read-dir", 
    "protocol-asset", 
    "window-request-user-attention", 
    "fs-read-file", 
    "dialog-open", 
    "dialog-save", 
    "dialog-ask",
    "dialog-message", 
    "shell-open", 
    "dialog-confirm",
    "fs-create-dir", 
    "fs-exists",
    "fs-write-file", 
    "http-request",
    "notification-all",
    "path-all", 
    "updater", 
    "window-close", 
    "window-hide",
    "window-maximize",
    "window-minimize",
    "window-show",
    "window-start-dragging",
    "window-unmaximize",
    "window-unminimize"] }
minecraft-launcher-lib = { path = "../launcher-lib"  }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
strip = true  # Remove debug symbols
opt-level = "s"  # Optimize for binary size
lto = true  # Enables link to optimizations
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
