[package]
name = "app"
version = "0.8.0"
description = "Minecraft Launcher and mod installer"
authors = ["Collin Blosser"]
license = "MIT"
repository = "https://github.com/VisualSource/rusty-mc-launcher"
default-run = "app"
edition = "2021"
rust-version = "1.80.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc.2", features = [] }

[dependencies]
tokio = { version = "1.39.2", features = ["sync"] }
log = "0.4.22"
copy_dir = "0.1.3"
thiserror = "1.0"
serde_json = "1.0"
time = "0.3.36"
httparse = "1.9.4"
serde = { version = "1.0", features = ["derive"] }
tauri-plugin-single-instance = "2.0.0-rc.0"
#tauri-plugin-sqlite = { git="https://github.com/lzdyes/tauri-plugin-sqlite", tag = "v0.1.1" }
tauri-plugin-log = "2.0.0-rc.0"
tauri-plugin-deep-link = "2.0.0-rc.0"
# old feature "http-multipart"
tauri = { version = "2.0.0-rc.2", features = [ "protocol-asset" ] }
minecraft-launcher-lib = { path = "../launcher-lib"  }
tauri-plugin-dialog = "2.0.0-rc.0"
tauri-plugin-fs = "2.0.0-rc.0"
tauri-plugin-http = {version ="2.0.0-rc.0", features = ["multipart"] }
tauri-plugin-process = "2.0.0-rc.0"
tauri-plugin-shell = "2.0.0-rc.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
strip = true  # Remove debug symbols
opt-level = "s"  # Optimize for binary size
lto = true  # Enables link to optimizations
codegen-units = 1 # Compile crates one after another so the compiler can optimize better

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.0.0-rc.0"
