[package]
name = "app"
version = "0.1.0-alpha"
description = "A Minecraft"
authors = ["VisualSource"]
license = "MIT"
repository = "https://github.com/VisualSource/rusty-mc-launcher"
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.12", features = [] }

[dev-dependencies]
tokio = { version = "1.18.2", features = [ "test-util", "macros" ] }

[dependencies]
log = "0.4.17"
log4rs = { version = "1.1.1", features = ["background_rotation"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.14", features = ["api-all"] }
semver_rs = "0.2.0"
app_dirs2 = "2.5.0"
mc-laucher-lib-rs = { path = "./mc-laucher-lib-rs" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
