[package]
name = "app"
version = "0.8.0"
description = "Minecraft Launcher and mod installer"
authors = ["Collin Blosser"]
license = "MIT"
repository = "https://github.com/VisualSource/rusty-mc-launcher"
default-run = "app"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc.9", features = [] }

[dependencies]
oauth2 = "4.4.2"
# old feature "protocol-asset"
tauri = { version = "2.0.0-rc.10", features = ["protocol-asset"  ] }
tauri-plugin-http = {version ="2.0.0-rc.3", features = ["multipart"] }
tauri-plugin-single-instance = "2.0.0-rc.1"
tauri-plugin-deep-link = "2.0.0-rc.3"
tauri-plugin-process = "2.0.0-rc.1"
tauri-plugin-dialog = "2.0.0-rc.5"
tauri-plugin-shell = "2.0.0-rc.3"
tauri-plugin-log = "2.0.0-rc.2"
tauri-plugin-fs = "2.0.0-rc.3"

minecraft-launcher-lib = { path = "../launcher-lib"  }
tokio = { version = "1.40.0", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
httparse = "1.9.4"
copy_dir = "0.1.3"
thiserror = "1.0"
time = "0.3.36"
log = "0.4.22"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.0.0-rc.3"
#[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
#default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
#custom-protocol = [ "tauri/custom-protocol" ]

#[profile.release]
#strip = true  # Remove debug symbols
#opt-level = "s"  # Optimize for binary size
#lto = true  # Enables link to optimizations
#codegen-units = 1 # Compile crates one after another so the compiler can optimize better


