[package]
name = "launcher-content"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = [ "test-util", "macros", "fs", "process","sync"] }
serde = {  workspace = true, features = ["derive"] }
time = { workspace = true, features = ["serde"]}
tokio-util = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

async_zip = { version = "0.0.17", features = ["tokio","tokio-fs","deflate"] }
reqwest = { version = "0.12.20", features = ["json"] }
sanitize-filename = "0.6.0"
normalize-path = "0.2.1"
lazy_static = "1.5.0"
futures = "0.3.31"
sha1 = "0.10.6"
hex = "0.4.3"

launcher-core = { path = "../launcher-core" }

[dev-dependencies]
env_logger = { workspace = true }