[package]
name = "app"
version = "0.9.0"
description = "Minecraft Launcher and mod installer"
default-run = "app"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
tauri = { workspace = true, features = ["protocol-asset"] }
tauri-plugin-http = {version ="2.4.4", features = ["multipart", "blocking", "json"] }
tauri-plugin-single-instance = { version ="2.2.4", features = ["deep-link"] }
tauri-plugin-deep-link = "2.3.0"
tauri-plugin-process = "2.2.1"
tauri-plugin-opener = "2.2.7"
tauri-plugin-dialog = "2.2.2"
tauri-plugin-shell = "2.2.1"
tauri-plugin-log = "2.4.0"
tauri-plugin-fs = "2.3.0"

launcher-core = { path ="../launcher-core"  }
openidconnect = { version = "4.0.0", default-features = false}
tokio = { workspace = true, features = ["sync"] }
serde = {  workspace = true, features = ["derive"] }
tokio-util = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
copy_dir = "0.1.3"
time = { workspace = true }
log = { workspace = true }
winreg = "0.55.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.7.1"



