/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedSettingsImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLayoutImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedLayoutCollectionsImport } from './routes/_authenticated/_layout/collections'
import { Route as AuthenticatedWorkshopSearchRouteImport } from './routes/_authenticated/workshop/search/route'
import { Route as AuthenticatedWorkshopProjectIdRouteImport } from './routes/_authenticated/workshop/project.$id/route'
import { Route as AuthenticatedWorkshopCurseforgeIdRouteImport } from './routes/_authenticated/workshop/curseforge.$id/route'
import { Route as AuthenticatedLayoutProfileProfileIdImport } from './routes/_authenticated/_layout/profile/_profile.$id'
import { Route as AuthenticatedLayoutProfileProfileIdIndexImport } from './routes/_authenticated/_layout/profile/_profile.$id/index'
import { Route as AuthenticatedLayoutProfileProfileIdScreenshotsImport } from './routes/_authenticated/_layout/profile/_profile.$id/screenshots'
import { Route as AuthenticatedLayoutProfileProfileIdEditImport } from './routes/_authenticated/_layout/profile/_profile.$id/edit'

// Create Virtual Routes

const AuthenticatedSkinsLazyImport = createFileRoute('/_authenticated/skins')()
const AuthenticatedPatchNotesLazyImport = createFileRoute(
  '/_authenticated/patch-notes',
)()
const AuthenticatedDownloadsLazyImport = createFileRoute(
  '/_authenticated/downloads',
)()
const AuthenticatedCreateProfileLazyImport = createFileRoute(
  '/_authenticated/create-profile',
)()
const AuthenticatedLayoutIndexLazyImport = createFileRoute(
  '/_authenticated/_layout/',
)()
const AuthenticatedSettingsGameLazyImport = createFileRoute(
  '/_authenticated/settings/game',
)()
const AuthenticatedSettingsDownloadLazyImport = createFileRoute(
  '/_authenticated/settings/download',
)()
const AuthenticatedSettingsAccountsLazyImport = createFileRoute(
  '/_authenticated/settings/accounts',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSkinsLazyRoute = AuthenticatedSkinsLazyImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/skins.lazy').then((d) => d.Route),
)

const AuthenticatedPatchNotesLazyRoute =
  AuthenticatedPatchNotesLazyImport.update({
    id: '/patch-notes',
    path: '/patch-notes',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/patch-notes.lazy').then((d) => d.Route),
  )

const AuthenticatedDownloadsLazyRoute = AuthenticatedDownloadsLazyImport.update(
  {
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/downloads.lazy').then((d) => d.Route),
)

const AuthenticatedCreateProfileLazyRoute =
  AuthenticatedCreateProfileLazyImport.update({
    id: '/create-profile',
    path: '/create-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/create-profile.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRoute = AuthenticatedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLayoutRoute = AuthenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLayoutIndexLazyRoute =
  AuthenticatedLayoutIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_layout/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any,
)

const AuthenticatedSettingsGameLazyRoute =
  AuthenticatedSettingsGameLazyImport.update({
    id: '/game',
    path: '/game',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/game.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsDownloadLazyRoute =
  AuthenticatedSettingsDownloadLazyImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/download.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountsLazyRoute =
  AuthenticatedSettingsAccountsLazyImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/accounts.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedLayoutCollectionsRoute =
  AuthenticatedLayoutCollectionsImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedWorkshopSearchRouteRoute =
  AuthenticatedWorkshopSearchRouteImport.update({
    id: '/workshop/search',
    path: '/workshop/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/workshop/search/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedWorkshopProjectIdRouteRoute =
  AuthenticatedWorkshopProjectIdRouteImport.update({
    id: '/workshop/project/$id',
    path: '/workshop/project/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/workshop/project.$id/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedWorkshopCurseforgeIdRouteRoute =
  AuthenticatedWorkshopCurseforgeIdRouteImport.update({
    id: '/workshop/curseforge/$id',
    path: '/workshop/curseforge/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/workshop/curseforge.$id/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedLayoutProfileProfileIdRoute =
  AuthenticatedLayoutProfileProfileIdImport.update({
    id: '/profile/_profile/$id',
    path: '/profile/$id',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutProfileProfileIdIndexRoute =
  AuthenticatedLayoutProfileProfileIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutProfileProfileIdRoute,
  } as any)

const AuthenticatedLayoutProfileProfileIdScreenshotsRoute =
  AuthenticatedLayoutProfileProfileIdScreenshotsImport.update({
    id: '/screenshots',
    path: '/screenshots',
    getParentRoute: () => AuthenticatedLayoutProfileProfileIdRoute,
  } as any)

const AuthenticatedLayoutProfileProfileIdEditRoute =
  AuthenticatedLayoutProfileProfileIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedLayoutProfileProfileIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/create-profile': {
      id: '/_authenticated/create-profile'
      path: '/create-profile'
      fullPath: '/create-profile'
      preLoaderRoute: typeof AuthenticatedCreateProfileLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/patch-notes': {
      id: '/_authenticated/patch-notes'
      path: '/patch-notes'
      fullPath: '/patch-notes'
      preLoaderRoute: typeof AuthenticatedPatchNotesLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/skins': {
      id: '/_authenticated/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof AuthenticatedSkinsLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/workshop/search': {
      id: '/_authenticated/workshop/search'
      path: '/workshop/search'
      fullPath: '/workshop/search'
      preLoaderRoute: typeof AuthenticatedWorkshopSearchRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_layout/collections': {
      id: '/_authenticated/_layout/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedLayoutCollectionsImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/settings/accounts': {
      id: '/_authenticated/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthenticatedSettingsAccountsLazyImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/settings/download': {
      id: '/_authenticated/settings/download'
      path: '/download'
      fullPath: '/settings/download'
      preLoaderRoute: typeof AuthenticatedSettingsDownloadLazyImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/settings/game': {
      id: '/_authenticated/settings/game'
      path: '/game'
      fullPath: '/settings/game'
      preLoaderRoute: typeof AuthenticatedSettingsGameLazyImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexLazyImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/workshop/curseforge/$id': {
      id: '/_authenticated/workshop/curseforge/$id'
      path: '/workshop/curseforge/$id'
      fullPath: '/workshop/curseforge/$id'
      preLoaderRoute: typeof AuthenticatedWorkshopCurseforgeIdRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/workshop/project/$id': {
      id: '/_authenticated/workshop/project/$id'
      path: '/workshop/project/$id'
      fullPath: '/workshop/project/$id'
      preLoaderRoute: typeof AuthenticatedWorkshopProjectIdRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_layout/profile/_profile/$id': {
      id: '/_authenticated/_layout/profile/_profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedLayoutProfileProfileIdImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/profile/_profile/$id/edit': {
      id: '/_authenticated/_layout/profile/_profile/$id/edit'
      path: '/edit'
      fullPath: '/profile/$id/edit'
      preLoaderRoute: typeof AuthenticatedLayoutProfileProfileIdEditImport
      parentRoute: typeof AuthenticatedLayoutProfileProfileIdImport
    }
    '/_authenticated/_layout/profile/_profile/$id/screenshots': {
      id: '/_authenticated/_layout/profile/_profile/$id/screenshots'
      path: '/screenshots'
      fullPath: '/profile/$id/screenshots'
      preLoaderRoute: typeof AuthenticatedLayoutProfileProfileIdScreenshotsImport
      parentRoute: typeof AuthenticatedLayoutProfileProfileIdImport
    }
    '/_authenticated/_layout/profile/_profile/$id/': {
      id: '/_authenticated/_layout/profile/_profile/$id/'
      path: '/'
      fullPath: '/profile/$id/'
      preLoaderRoute: typeof AuthenticatedLayoutProfileProfileIdIndexImport
      parentRoute: typeof AuthenticatedLayoutProfileProfileIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedLayoutProfileProfileIdRouteChildren {
  AuthenticatedLayoutProfileProfileIdEditRoute: typeof AuthenticatedLayoutProfileProfileIdEditRoute
  AuthenticatedLayoutProfileProfileIdScreenshotsRoute: typeof AuthenticatedLayoutProfileProfileIdScreenshotsRoute
  AuthenticatedLayoutProfileProfileIdIndexRoute: typeof AuthenticatedLayoutProfileProfileIdIndexRoute
}

const AuthenticatedLayoutProfileProfileIdRouteChildren: AuthenticatedLayoutProfileProfileIdRouteChildren =
  {
    AuthenticatedLayoutProfileProfileIdEditRoute:
      AuthenticatedLayoutProfileProfileIdEditRoute,
    AuthenticatedLayoutProfileProfileIdScreenshotsRoute:
      AuthenticatedLayoutProfileProfileIdScreenshotsRoute,
    AuthenticatedLayoutProfileProfileIdIndexRoute:
      AuthenticatedLayoutProfileProfileIdIndexRoute,
  }

const AuthenticatedLayoutProfileProfileIdRouteWithChildren =
  AuthenticatedLayoutProfileProfileIdRoute._addFileChildren(
    AuthenticatedLayoutProfileProfileIdRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutCollectionsRoute: typeof AuthenticatedLayoutCollectionsRoute
  AuthenticatedLayoutIndexLazyRoute: typeof AuthenticatedLayoutIndexLazyRoute
  AuthenticatedLayoutProfileProfileIdRoute: typeof AuthenticatedLayoutProfileProfileIdRouteWithChildren
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutCollectionsRoute: AuthenticatedLayoutCollectionsRoute,
  AuthenticatedLayoutIndexLazyRoute: AuthenticatedLayoutIndexLazyRoute,
  AuthenticatedLayoutProfileProfileIdRoute:
    AuthenticatedLayoutProfileProfileIdRouteWithChildren,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountsLazyRoute: typeof AuthenticatedSettingsAccountsLazyRoute
  AuthenticatedSettingsDownloadLazyRoute: typeof AuthenticatedSettingsDownloadLazyRoute
  AuthenticatedSettingsGameLazyRoute: typeof AuthenticatedSettingsGameLazyRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountsLazyRoute:
    AuthenticatedSettingsAccountsLazyRoute,
  AuthenticatedSettingsDownloadLazyRoute:
    AuthenticatedSettingsDownloadLazyRoute,
  AuthenticatedSettingsGameLazyRoute: AuthenticatedSettingsGameLazyRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedCreateProfileLazyRoute: typeof AuthenticatedCreateProfileLazyRoute
  AuthenticatedDownloadsLazyRoute: typeof AuthenticatedDownloadsLazyRoute
  AuthenticatedPatchNotesLazyRoute: typeof AuthenticatedPatchNotesLazyRoute
  AuthenticatedSkinsLazyRoute: typeof AuthenticatedSkinsLazyRoute
  AuthenticatedWorkshopSearchRouteRoute: typeof AuthenticatedWorkshopSearchRouteRoute
  AuthenticatedWorkshopCurseforgeIdRouteRoute: typeof AuthenticatedWorkshopCurseforgeIdRouteRoute
  AuthenticatedWorkshopProjectIdRouteRoute: typeof AuthenticatedWorkshopProjectIdRouteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedCreateProfileLazyRoute: AuthenticatedCreateProfileLazyRoute,
  AuthenticatedDownloadsLazyRoute: AuthenticatedDownloadsLazyRoute,
  AuthenticatedPatchNotesLazyRoute: AuthenticatedPatchNotesLazyRoute,
  AuthenticatedSkinsLazyRoute: AuthenticatedSkinsLazyRoute,
  AuthenticatedWorkshopSearchRouteRoute: AuthenticatedWorkshopSearchRouteRoute,
  AuthenticatedWorkshopCurseforgeIdRouteRoute:
    AuthenticatedWorkshopCurseforgeIdRouteRoute,
  AuthenticatedWorkshopProjectIdRouteRoute:
    AuthenticatedWorkshopProjectIdRouteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedLayoutRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/create-profile': typeof AuthenticatedCreateProfileLazyRoute
  '/downloads': typeof AuthenticatedDownloadsLazyRoute
  '/patch-notes': typeof AuthenticatedPatchNotesLazyRoute
  '/skins': typeof AuthenticatedSkinsLazyRoute
  '/workshop/search': typeof AuthenticatedWorkshopSearchRouteRoute
  '/collections': typeof AuthenticatedLayoutCollectionsRoute
  '/settings/accounts': typeof AuthenticatedSettingsAccountsLazyRoute
  '/settings/download': typeof AuthenticatedSettingsDownloadLazyRoute
  '/settings/game': typeof AuthenticatedSettingsGameLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/': typeof AuthenticatedLayoutIndexLazyRoute
  '/workshop/curseforge/$id': typeof AuthenticatedWorkshopCurseforgeIdRouteRoute
  '/workshop/project/$id': typeof AuthenticatedWorkshopProjectIdRouteRoute
  '/profile/$id': typeof AuthenticatedLayoutProfileProfileIdRouteWithChildren
  '/profile/$id/edit': typeof AuthenticatedLayoutProfileProfileIdEditRoute
  '/profile/$id/screenshots': typeof AuthenticatedLayoutProfileProfileIdScreenshotsRoute
  '/profile/$id/': typeof AuthenticatedLayoutProfileProfileIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/create-profile': typeof AuthenticatedCreateProfileLazyRoute
  '/downloads': typeof AuthenticatedDownloadsLazyRoute
  '/patch-notes': typeof AuthenticatedPatchNotesLazyRoute
  '/skins': typeof AuthenticatedSkinsLazyRoute
  '/workshop/search': typeof AuthenticatedWorkshopSearchRouteRoute
  '/collections': typeof AuthenticatedLayoutCollectionsRoute
  '/settings/accounts': typeof AuthenticatedSettingsAccountsLazyRoute
  '/settings/download': typeof AuthenticatedSettingsDownloadLazyRoute
  '/settings/game': typeof AuthenticatedSettingsGameLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/': typeof AuthenticatedLayoutIndexLazyRoute
  '/workshop/curseforge/$id': typeof AuthenticatedWorkshopCurseforgeIdRouteRoute
  '/workshop/project/$id': typeof AuthenticatedWorkshopProjectIdRouteRoute
  '/profile/$id/edit': typeof AuthenticatedLayoutProfileProfileIdEditRoute
  '/profile/$id/screenshots': typeof AuthenticatedLayoutProfileProfileIdScreenshotsRoute
  '/profile/$id': typeof AuthenticatedLayoutProfileProfileIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/create-profile': typeof AuthenticatedCreateProfileLazyRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsLazyRoute
  '/_authenticated/patch-notes': typeof AuthenticatedPatchNotesLazyRoute
  '/_authenticated/skins': typeof AuthenticatedSkinsLazyRoute
  '/_authenticated/workshop/search': typeof AuthenticatedWorkshopSearchRouteRoute
  '/_authenticated/_layout/collections': typeof AuthenticatedLayoutCollectionsRoute
  '/_authenticated/settings/accounts': typeof AuthenticatedSettingsAccountsLazyRoute
  '/_authenticated/settings/download': typeof AuthenticatedSettingsDownloadLazyRoute
  '/_authenticated/settings/game': typeof AuthenticatedSettingsGameLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/_layout/': typeof AuthenticatedLayoutIndexLazyRoute
  '/_authenticated/workshop/curseforge/$id': typeof AuthenticatedWorkshopCurseforgeIdRouteRoute
  '/_authenticated/workshop/project/$id': typeof AuthenticatedWorkshopProjectIdRouteRoute
  '/_authenticated/_layout/profile/_profile/$id': typeof AuthenticatedLayoutProfileProfileIdRouteWithChildren
  '/_authenticated/_layout/profile/_profile/$id/edit': typeof AuthenticatedLayoutProfileProfileIdEditRoute
  '/_authenticated/_layout/profile/_profile/$id/screenshots': typeof AuthenticatedLayoutProfileProfileIdScreenshotsRoute
  '/_authenticated/_layout/profile/_profile/$id/': typeof AuthenticatedLayoutProfileProfileIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/settings'
    | '/create-profile'
    | '/downloads'
    | '/patch-notes'
    | '/skins'
    | '/workshop/search'
    | '/collections'
    | '/settings/accounts'
    | '/settings/download'
    | '/settings/game'
    | '/settings/'
    | '/'
    | '/workshop/curseforge/$id'
    | '/workshop/project/$id'
    | '/profile/$id'
    | '/profile/$id/edit'
    | '/profile/$id/screenshots'
    | '/profile/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/create-profile'
    | '/downloads'
    | '/patch-notes'
    | '/skins'
    | '/workshop/search'
    | '/collections'
    | '/settings/accounts'
    | '/settings/download'
    | '/settings/game'
    | '/settings'
    | '/'
    | '/workshop/curseforge/$id'
    | '/workshop/project/$id'
    | '/profile/$id/edit'
    | '/profile/$id/screenshots'
    | '/profile/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_layout'
    | '/_authenticated/settings'
    | '/_authenticated/create-profile'
    | '/_authenticated/downloads'
    | '/_authenticated/patch-notes'
    | '/_authenticated/skins'
    | '/_authenticated/workshop/search'
    | '/_authenticated/_layout/collections'
    | '/_authenticated/settings/accounts'
    | '/_authenticated/settings/download'
    | '/_authenticated/settings/game'
    | '/_authenticated/settings/'
    | '/_authenticated/_layout/'
    | '/_authenticated/workshop/curseforge/$id'
    | '/_authenticated/workshop/project/$id'
    | '/_authenticated/_layout/profile/_profile/$id'
    | '/_authenticated/_layout/profile/_profile/$id/edit'
    | '/_authenticated/_layout/profile/_profile/$id/screenshots'
    | '/_authenticated/_layout/profile/_profile/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_layout",
        "/_authenticated/settings",
        "/_authenticated/create-profile",
        "/_authenticated/downloads",
        "/_authenticated/patch-notes",
        "/_authenticated/skins",
        "/_authenticated/workshop/search",
        "/_authenticated/workshop/curseforge/$id",
        "/_authenticated/workshop/project/$id"
      ]
    },
    "/_authenticated/_layout": {
      "filePath": "_authenticated/_layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_layout/collections",
        "/_authenticated/_layout/",
        "/_authenticated/_layout/profile/_profile/$id"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/accounts",
        "/_authenticated/settings/download",
        "/_authenticated/settings/game",
        "/_authenticated/settings/"
      ]
    },
    "/_authenticated/create-profile": {
      "filePath": "_authenticated/create-profile.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/downloads": {
      "filePath": "_authenticated/downloads.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/patch-notes": {
      "filePath": "_authenticated/patch-notes.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/skins": {
      "filePath": "_authenticated/skins.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/workshop/search": {
      "filePath": "_authenticated/workshop/search/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_layout/collections": {
      "filePath": "_authenticated/_layout/collections.tsx",
      "parent": "/_authenticated/_layout"
    },
    "/_authenticated/settings/accounts": {
      "filePath": "_authenticated/settings/accounts.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/download": {
      "filePath": "_authenticated/settings/download.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/game": {
      "filePath": "_authenticated/settings/game.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/_layout/": {
      "filePath": "_authenticated/_layout/index.lazy.tsx",
      "parent": "/_authenticated/_layout"
    },
    "/_authenticated/workshop/curseforge/$id": {
      "filePath": "_authenticated/workshop/curseforge.$id/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/workshop/project/$id": {
      "filePath": "_authenticated/workshop/project.$id/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_layout/profile/_profile/$id": {
      "filePath": "_authenticated/_layout/profile/_profile.$id.tsx",
      "parent": "/_authenticated/_layout",
      "children": [
        "/_authenticated/_layout/profile/_profile/$id/edit",
        "/_authenticated/_layout/profile/_profile/$id/screenshots",
        "/_authenticated/_layout/profile/_profile/$id/"
      ]
    },
    "/_authenticated/_layout/profile/_profile/$id/edit": {
      "filePath": "_authenticated/_layout/profile/_profile.$id/edit.tsx",
      "parent": "/_authenticated/_layout/profile/_profile/$id"
    },
    "/_authenticated/_layout/profile/_profile/$id/screenshots": {
      "filePath": "_authenticated/_layout/profile/_profile.$id/screenshots.tsx",
      "parent": "/_authenticated/_layout/profile/_profile/$id"
    },
    "/_authenticated/_layout/profile/_profile/$id/": {
      "filePath": "_authenticated/_layout/profile/_profile.$id/index.tsx",
      "parent": "/_authenticated/_layout/profile/_profile/$id"
    }
  }
}
ROUTE_MANIFEST_END */
