[package]
name = "launcher-process"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = {  workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["test-util", "fs"] }
thiserror = { workspace = true }
log = { workspace = true }