[default]
description = "Default permissions for the rmcl-auth plugin"
permissions = ["allow-authenticate","allow-logout","allow-refresh"]

[[permission]]
identifier = "allow-authenticate"
description = "Allow to start authentication flow"
commands.allow = ["authenticate","mr_authenticate"]

[[permission]]
identifier = "allow-logout"
description = "Allow logout"
commands.allow = ["logout"]

[[permission]]
identifier = "allow-refresh"
description = "Allow refresh"
commands.allow = ["refresh"]


