[package]
name = "launcher-installer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
launcher-core = { path = "../launcher-core" }