[default]
description = "Default permissions for the rmcl-auth plugin"
permissions = ["allow-authenticate","allow-logout"]

[[permission]]
identifier = "allow-authenticate"
description = "Allow to start authentication flow"
commands.allow = ["authenticate"]

[[permission]]
identifier = "allow-logout"
description = "Allow logout"
commands.allow = ["logout"]