name: "Publish"

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
      runs-on: ${{ matrix.platform }}
      steps:
        - uses: actions/checkout@v3
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install Rust stable
          uses: dtolnay/rust-toolchain@stable
        - name: Rust Cache
          uses: Swatinem/rust-cache@v2.2.1 #https://github.com/marketplace/actions/rust-cache
          with:
            working-directory: ./src-tauri
        - name: Node Cache
          uses: actions/cache@v3 #https://github.com/marketplace/actions/cache
          id: npm-cache
          with:
            path: node_modules
            key: node-modules-${{ hashFiles('package-lock.json') }}
        - name: install dependencies (ubuntu only)
          if: matrix.platform == 'ubuntu-20.04'
          run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        - name: Install node_modules
          if: steps.npm-cache.outputs.cache-hit != 'true'
          run: npm install
        - uses: tauri-apps/tauri-action@v0 # https://github.com/tauri-apps/tauri-action
          env:
            TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
            TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
            releaseName: "Rusty Minecraft Launcher v__VERSION__"
            releaseBody: "See the assets to download this version and install."
            releaseDraft: true
            prerelease: false
