name: Show Me the S3cr3tz
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.TAURI_KEY_PASSWORD} | sed 's/./& /g'
        echo ${{secrets.TAURI_PRIVATE_KEY}} | sed 's/./& /g'
